core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('blocks/<int:pk>/', views.DetailView.as_view(), name='block')
]

testblockchain/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/models.py
from django.db import models


class Block(models.Model):
    """Модель бля блока"""
    height = models.IntegerField('Высота блока', primary_key=True)
    hash = models.CharField('Хэш блока', max_length=64)
    timestamp = models.DateTimeField('Таймштамп блока')
    miner_address = models.CharField('Адресс майнера', max_length=34)
    tx_count = models.IntegerField('Число транзакций в блоке')

    def __str__(self):
        return f'Блок - высота ({self.height}), хэш ({self.hash})'

    class Meta:
        verbose_name = "Блок"
        verbose_name_plural = "Блоки"

core/views.py
from django.shortcuts import render

from django.views import generic
from core.models import Block


class IndexView(generic.ListView):
    """Главная страница, список всех блоков"""
    paginate_by = 50
    model = Block
    template_name = 'core/index.html'
    context_object_name = 'blocks'

    def get_queryset(self):
        return Block.objects.order_by('-height')


class DetailView(generic.DetailView):
    """Подробная страница для блоков"""
    model = Block
    template_name = 'core/detail.html'
    context_object_name = 'block_ob'

templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}Тестовое задания{% endblock %}</title>
</head>

<body class="pb-5">
    <div class="container">
        <h1 class="row">
            <div class="col-12 pt-3 pb-4">Тестовое задание для стажировки (Python Developer)</div>
        </h1>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/core/detail.html
{% extends "core/base.html" %}

{% block content %}
        <div class="container">
            <div class="row">
                <h2 class="col-12">Информация о блоке #{{ block_ob.height }}</h2>
            </div>
            <div class="row">
                <div class="col-12">Высота блока: {{ block_ob.height }}</div>
                <div class="col-12">Хэш блока: {{ block_ob.hash }}</div>
                <div class="col-12">Время: {{ block_ob.timestamp }}</div>
                <div class="col-12">Майнер: {{ block_ob.miner_address }}</div>
                <div class="col-12">Транзакций: {{ block_ob.tx_count }}</div>
            </div>
        </div>

{% endblock %}

templates/core/index.html
{% extends "core/base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <h2 class="col-12">Блоки</h2>
        </div>
        {% for block in blocks %}
            <div class="row mb-2">
                <div class="col-auto">
                    <a href="{% url 'core:block' block.height %}" class="d-block w-100 block-link">
                        Блок #{{ block.height }} <br>
                        {{ block.timestamp }}
                    </a>
                </div>
                <div class="col-9">
                    <div>Добыто: {{ block.miner_address }}</div>
                    <div>{{ block.tx_count }} транзакции</div>
                </div>
            </div>
        {% endfor %}
        <div class="row">
            <div class="col-12">
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; первая</a>
                            <a href="?page={{ page_obj.previous_page_number }}">пред.</a>
                        {% endif %}

                        <span class="current">
                            Стр {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">след.</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}